
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSIGN ID IF LBRACE LPAREN NUM OPTR RBRACE RPAREN SEMI WHILEprogram : stmtliststmt : ID ASSIGN expr SEMIstmt : LBRACE stmtlist RBRACEstmt : IF LPAREN expr RPAREN stmtstmt : WHILE LPAREN expr RPAREN stmtstmtlist : stmtstmtlist : stmtlist stmtexpr : IDexpr : NUMexpr : expr OPTR expr'
    
_lr_action_items = {'ID':([0,2,3,5,8,9,10,11,12,16,19,20,21,22,24,25,],[4,4,-6,4,-7,13,4,13,13,-3,-2,13,4,4,-4,-5,]),'LBRACE':([0,2,3,5,8,10,16,19,21,22,24,25,],[5,5,-6,5,-7,5,-3,-2,5,5,-4,-5,]),'IF':([0,2,3,5,8,10,16,19,21,22,24,25,],[6,6,-6,6,-7,6,-3,-2,6,6,-4,-5,]),'WHILE':([0,2,3,5,8,10,16,19,21,22,24,25,],[7,7,-6,7,-7,7,-3,-2,7,7,-4,-5,]),'$end':([1,2,3,8,16,19,24,25,],[0,-1,-6,-7,-3,-2,-4,-5,]),'RBRACE':([3,8,10,16,19,24,25,],[-6,-7,16,-3,-2,-4,-5,]),'ASSIGN':([4,],[9,]),'LPAREN':([6,7,],[11,12,]),'NUM':([9,11,12,20,],[15,15,15,15,]),'SEMI':([13,14,15,23,],[-8,19,-9,-10,]),'OPTR':([13,14,15,17,18,23,],[-8,20,-9,20,20,20,]),'RPAREN':([13,15,17,18,23,],[-8,-9,21,22,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'stmtlist':([0,5,],[2,10,]),'stmt':([0,2,5,10,21,22,],[3,8,3,8,24,25,]),'expr':([9,11,12,20,],[14,17,18,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> stmtlist','program',1,'p_program','MiniCParser.py',6),
  ('stmt -> ID ASSIGN expr SEMI','stmt',4,'p_stmt_expr_semi_assign','MiniCParser.py',11),
  ('stmt -> LBRACE stmtlist RBRACE','stmt',3,'p_stmt_brace','MiniCParser.py',16),
  ('stmt -> IF LPAREN expr RPAREN stmt','stmt',5,'p_stmt_if','MiniCParser.py',21),
  ('stmt -> WHILE LPAREN expr RPAREN stmt','stmt',5,'p_stmt_while','MiniCParser.py',26),
  ('stmtlist -> stmt','stmtlist',1,'p_stmtlist_single','MiniCParser.py',31),
  ('stmtlist -> stmtlist stmt','stmtlist',2,'p_stmtlist_multiple','MiniCParser.py',36),
  ('expr -> ID','expr',1,'p_expr_id','MiniCParser.py',41),
  ('expr -> NUM','expr',1,'p_expr_num','MiniCParser.py',46),
  ('expr -> expr OPTR expr','expr',3,'p_expr_optr','MiniCParser.py',51),
]
